export default {
  ru: {
    index: 'ru',
    loadTextures: 'загрузка текстур',
    loadWorld: 'загрузка мира',
    gameName: 'просто\nстратегия',
    map1: 'карта 1',
    play: 'играть',
    launch: 'запуск...',
    shutdown: 'завершение...',
    ai: 'ИИ',
    easy: 'легкий',
    normal: 'нормальный',
    target: 'цель',
    targetDiscr: 'Найдите и захватите столичную клетку противника',
    notEnought: 'недостаточно',
    wrongPlace: 'неподходящее\nместо',
    underAtack: 'на нас напали',
    enemyBaseSited: 'вражеская столица обнаружена!',
    cityLost: 'противник отбил город!',
    cityClamed: 'город захвачен!',
    surroundBase: 'окружите столицу для захвата',
    win: 'победа',
    lose: 'поражение',
    tie: 'ничья',
    continue: 'продолжить',
    timeIsUp: 'время вышло',
    yourBaseHasCaptured: 'ваша столица захвачена',
    enemyBaseHasCaptured: 'столица противника захвачена',
    youOutOfHexes: 'у вас закончились плитки',
    enemyOutOfHexes: 'у противника законичились плитки',
    youSurrendered: 'Вы сдались',
    enemySurrendered: 'Противник сдался',
    timeSpend: 'Затраченное время',
    result: 'результат',
    tilesLeft: 'плиток осталось',
    menu: 'меню',
    settings: 'настройки',
    surrenderAndLeave: 'сдаться и выйти',
    tiles: 'плиток',
    superTiles: 'супер-плиток',
    landTroops: 'высадить войска?',
    yes: 'да',
    no: 'нет',
    enemyLeft: 'противник вышел из игры',
    youLeft: 'вы вышли из игры',
  },
  en: {
    index: 'ru',
  }
}