export default {
  ru: {
    index: 'ru',
    loadTextures: 'загрузка текстур',
    loadWorld: 'загрузка мира',
    gameName: 'просто\nстратегия',
    map1: 'карта 1',
    play: 'играть',
    launch: 'запуск...',
    shutdown: 'завершение...',
    ai: 'ИИ',
    easy: 'лёгкий',
    normal: 'нормальный',
    hard: 'сложный',
    target: 'цель',
    targetDiscr: 'Найдите и захватите столичную клетку противника',
    notEnought: 'недостаточно',
    wrongPlace: 'неподходящее\nместо',
    claming: 'идет захват',
    upgrading: 'идет улучшение',
    underAtack: 'на нас напали',
    enemyBaseSited: 'вражеская столица обнаружена!',
    cityLost: 'противник отбил город!',
    cityClamed: 'город захвачен!',
    surroundBase: 'окружите столицу для захвата',
    win: 'победа!',
    lose: 'поражение!',
    tie: 'ничья',
    continue: 'далее',
    timeIsUp: 'время вышло',
    yourBaseHasCaptured: 'ваша столица захвачена',
    enemyBaseHasCaptured: 'столица противника захвачена',
    youOutOfHexes: 'у вас закончились плитки',
    enemyOutOfHexes: 'у противника законичились плитки',
    youSurrendered: 'Вы сдались',
    enemySurrendered: 'Противник сдался',
    timeSpend: 'Времени затрачено',
    result: 'результат',
    tilesLeft: 'плиток осталось',
    menu: 'меню',
    settings: 'настройки',
    surrenderAndLeave: 'сдаться и выйти',
    tiles: 'плиток',
    superTiles: 'супер-плиток',
    landTroops: 'Отправить десант?',
    yes: 'да',
    no: 'нет',
    enemyLeft: 'противник вышел из игры',
    youLeft: 'вы вышли из игры',
    escapeBtn: 'сдаться и выйти',
    settingsBtn: 'настройки',
    singleplayerBtn: 'одиночный режим',
    multiplayerBtn: 'мультиплеер',
    repeatBtn: 'повторить поиск',
    choiceOfDifficulty: 'выбор сложности',
    timeLeft: 'осталось',
    searchEnemy: 'поиск соперника',
    cantLevelUp: 'невозможно улучшить',
    points: 'Очков:'
  },
  en: {
    index: 'ru',
  }
}